# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Talaat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Talaat

  target 'TalaatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TalaatUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
